name: executor_lib
description: Provides an abstraction for executing jobs.
version: 0.3.0
homepage: https://github.com/greensopinion/executor_lib

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  async: ^2.8.2

dev_dependencies:
  lints: ^2.0.1
  flutter_test:
    sdk: flutter