name: executors
description: Provides an abstraction for executing jobs.
version: 0.1.0
homepage: https://github.com/greensopinion/executors

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.14.0"

dependencies:
  flutter:
    sdk: flutter
  async: ^2.8.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
